### ISSUE TITLE
Return non-zero exit code on unsuccessful operation and write error message to stderr.

### ISSUE THREAD

**Issue by SamuelSwartzberg** [waldirborbajr/kvstok#39]
Description
-------------

Return non-zero exit code on unsuccessful operation, write error message to stderr.

Steps to Reproduce
------------------

1. ` kvstok getkv foo` (where `foo` is currently not a key in the kvstore)
(Potentially also in other cases, such as deleting nonexistent keys, etc., though those are more arguable)

### Expected Behavior

Get an non-zero exit code, since the operation failed, and write an error message to stderr.

### Actual Behavior

Get a zero exit code, and write a message to stdout.

### Reasoning

Well-behaved CLI commands use error codes to indicate success/failure, and write error messages to stderr. Implementing this for this tool allows easier usage in more complex workflows that utilize this behavior, as well as allow ease of use by using familiar patterns.

**Comment by waldirborbajr** [comment]
Fixed exit code on error. Please verify and let me know if another change is necessary.

**Comment by SamuelSwartzberg** [comment]
@waldirborbajr Thanks so much! I'm taking some time off from developing at the moment, but will check when I'm back and report if I find any problems.
