### ISSUE TITLE
Error executing golangci-lint

### ISSUE THREAD

**Issue by waldirborbajr** [waldirborbajr/kvstok#6]
Trying to figure out why I'm getting this error :(

Error: Dependencies file is not found in /home/runner/work/kvstok/kvstok. Supported file pattern: go.sum

**Comment by nikzayn** [comment]
I'd like to take this up! Can you send some documented guide or any tutorial which I can follow before proceeding to it?

**Comment by waldirborbajr** [comment]
Hi @nikzayn I'll describe

**Comment by waldirborbajr** [comment]
Hi @nikzayn the main goal here, is to fix golanci-lint action to execute on every commit check to certify that everything is correct according. As a reference you can take a look here: https://github.com/golangci/golangci-lint-action

**Comment by waldirborbajr** [comment]
Fix error on execute lint. 
- Removed config file and adjust workflow script

**Comment by waldirborbajr** [comment]
@holopin-bot @nikzayn

**Comment by waldirborbajr** [comment]
@holopin-bot @nikzayn

**Comment by waldirborbajr** [comment]
@holopin-bot @nikzayn

**Comment by waldirborbajr** [comment]
@holopin-bot @nikzayn

**Comment by waldirborbajr** [comment]
@holopin-bot @nikzayn
